# Generated by Django 4.0.2 on 2022-06-03 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Comuna')),
                ('nombreComuna', models.CharField(max_length=30, verbose_name='Nombre Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=20, verbose_name='Apellidos')),
                ('correo', models.EmailField(max_length=20, verbose_name='Correo')),
                ('password', models.CharField(max_length=8, verbose_name='Contrasena')),
                ('fono', models.IntegerField(max_length=9, verbose_name='Fono')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOL.comuna', verbose_name='Comuna')),
            ],
        ),
    ]
