# Generated by Django 4.0.4 on 2022-06-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LOL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del producto')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre del producto')),
                ('imagen', models.ImageField(upload_to='img/', verbose_name='Imagen')),
                ('description', models.TextField(null=True, verbose_name='Descripcion')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('precio', models.IntegerField(verbose_name='precio del producto')),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellidos',
            field=models.CharField(max_length=30, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOL.comuna'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fono',
            field=models.IntegerField(verbose_name='Fono'),
        ),
    ]
